// Public copy: shared product facts with explicit French and English wording.
// Do not turn code, a submission or a tag into a claim of store availability.
export const productCopy = {
 LoadSense: {category:'training', en:['iPhone · iPad · Apple Watch','Make sense of your daily energy.','A clearer view of energy, sleep and recovery from Apple Health, with the context behind the numbers.'], fr:['iPhone · iPad · Apple Watch','Comprendre son énergie du jour.','Une lecture de votre énergie, de votre sommeil et de votre récupération à partir d’Apple Santé, avec le contexte derrière les chiffres.']},
 TempoReps: {category:'training', en:['iPhone · Apple Watch','Keep your eyes on the next rep.','Timers for intervals, strength sessions and rest. Large, readable cues help you follow the workout.'], fr:['iPhone · Apple Watch','Garder le rythme, jusqu’à la dernière répétition.','Des minuteurs pour vos intervalles, vos séances de musculation et vos temps de repos. Des repères lisibles pour suivre l’effort.']},
 PRVault: {category:'training', en:['iPhone · iPad','Your next record starts with the last one.','Keep your lifting, WOD and cardio records together, and find your reference before the next session.'], fr:['iPhone · iPad','Le prochain record commence par le précédent.','Retrouvez vos records de musculation, de WOD et de cardio pour aborder la prochaine séance avec un repère.']},
 GrooveLog: {category:'training', en:['iPhone','Small sets. A regular practice.','A Grease the Groove journal that helps you build a routine around frequent, manageable sets.'], fr:['iPhone','De petites séries, une pratique régulière.','Un carnet Grease the Groove pour installer une routine de séries fréquentes et accessibles.']},
 ColdLoad: {category:'training', en:['iPhone','The right plates, without the maths.','Set the weight you want to lift and see how to load the bar with the plates you have.'], fr:['iPhone','Les bons disques, sans calcul mental.','Indiquez la charge visée et voyez comment monter votre barre avec les disques disponibles.']},
 MoveAtlas: {category:'training', en:['iPhone','Find a movement that fits.','Browse exercises and prepare a workout around your equipment, time and training focus.'], fr:['iPhone','Trouver le mouvement qui convient.','Explorez les exercices et préparez une séance selon votre matériel, votre temps et les zones à travailler.']},
 FastZen: {category:'everyday', en:['iPhone','A simple rhythm for fasting.','Plan your fasting windows, follow the timer and use reminders to keep your chosen schedule close.'], fr:['iPhone','Un rythme simple pour le jeûne.','Planifiez vos plages de jeûne, suivez le minuteur et retrouvez vos horaires grâce aux rappels.']},
 NeatShift: {category:'everyday', en:['iPhone · iPad','Make room for a shared routine.','Organise household chores room by room, taking everyone’s availability into account.'], fr:['iPhone · iPad','Faire une place à chacun dans la routine.','Organisez les tâches de la maison pièce par pièce, en tenant compte des disponibilités de chacun.']},
 BrewMeter: {category:'everyday', en:['iPhone','Keep an eye on your caffeine.','Log your drinks and explore caffeine estimates in relation to the bedtime you choose.'], fr:['iPhone','Garder un œil sur sa caféine.','Notez vos boissons et consultez les estimations de caféine selon l’heure de coucher choisie.']},
 NoBuyCart: {category:'everyday', en:['iPhone','The pleasure of a cart. Without checkout.','Explore a fictional marketplace, fill a cart and keep track of what you chose not to spend.'], fr:['iPhone','Le plaisir du panier, sans passer en caisse.','Parcourez une boutique fictive, remplissez votre panier et visualisez ce que vous avez choisi de ne pas dépenser.']},
 PasDuJour: {category:'everyday', en:['Apple Watch','Your daily steps, at a glance.','Put a step count and a goal on your wrist, with complications and styles you can make your own.'], fr:['Apple Watch','Vos pas du jour, en un regard.','Retrouvez votre nombre de pas et votre objectif au poignet, avec des complications et des styles à personnaliser.']},
 'petites-gouttes': {category:'family', en:['iPhone','One less thing to remember.','Keep track of frozen breast milk, dates and the next bag to use. A practical companion for your stash.'], fr:['iPhone','Une chose de moins à retenir.','Retrouvez votre stock de lait maternel congelé, les dates et le prochain sachet à utiliser. Un repère concret au quotidien.']},
 'petites-bouchees': {category:'family', en:['iPhone','Remember every first taste.','Follow food introductions and record reactions in a journal you can return to as your baby discovers new flavours.'], fr:['iPhone','Se souvenir de chaque première bouchée.','Suivez les aliments introduits et notez les réactions dans un carnet à retrouver au fil des découvertes de bébé.']},
 'petites-nuits': {category:'family', en:['iPhone','A gentle record of little nights.','Note sleep, wakeups and feeds, then look back on your baby’s rhythm without relying on memory.'], fr:['iPhone','Un carnet doux pour les petites nuits.','Notez les périodes de sommeil, les réveils et les repas pour retrouver le rythme de bébé sans tout retenir.']},
 'petites-dents': {category:'family', en:['iPhone','Keep the story of every little tooth.','Record baby teeth as they arrive and keep their dates together in a timeline.'], fr:['iPhone','Garder l’histoire de chaque petite dent.','Notez l’arrivée des dents de lait et retrouvez leurs dates dans une chronologie.']},
 VesperDrift: {category:'play', en:['iPhone','One thumb. One more run.','A vertical arcade game of movement, timed attacks and a score to take a little further.'], fr:['iPhone','Un pouce. Encore une partie.','Un jeu d’arcade vertical où l’on se déplace, déclenche ses attaques au bon moment et pousse son score un peu plus loin.']},
 Echappee: {category:'play', en:['Apple silicon Mac','Turn the pedals. Let the road unfold.','A contemplative indoor cycling game with changing landscapes and a compatible FTMS smart trainer. iPhone and iPad versions are coming later.'], fr:['Mac Apple silicon','Tourner les jambes. Laisser la route venir.','Un jeu de cyclisme en intérieur contemplatif, des paysages changeants et un home trainer FTMS compatible. Les versions iPhone et iPad viendront plus tard.']},
};
export const copy = {
 en: {
  title:'Apps for everyday life — Benjamin Dupin', description:'Discover apps for training, everyday routines, life with a baby and indoor cycling. Explore real interfaces and find the app that fits your day.',
  skip:'Skip to content', nav:'Main navigation', apps:'Apps', contact:'App support', heroLabel:'Training · Everyday life · Baby & family', hero:'Your day.<br><em>Your kind of app.</em>', intro:'Keep a training rhythm, remember the little things or head out on a virtual ride. Find a companion for what matters in your day.', heroCta:'Find your next app', heroWork:'Explore the highlights', heroNote:'A timer. An energy journal. A road to explore.',
  selected:'01 / Selected products', selectedTitle:'Different days.<br>Different tools.', selectedIntro:'For your next session, a quieter ride or the small logistics of family life. Each product starts with a particular need.',
  discover:'Explore', realShot:'Product screenshots', loadsenseCaption:'LoadSense · Daily energy view', familyCaption:'Petites Gouttes · Milk stash overview', echappeeCaption:'Échappée · Real game capture · Seed 52025, km 8.3, 17:45',
  loadsenseTitle:'Read your energy.<br>Understand the context.', loadsenseText:'Sleep, recovery and activity tell different parts of the story. LoadSense puts them in one place, with the evidence behind its estimates.', loadsenseNote:'Health estimates for personal context. Not a medical device.',
  echappeeTitle:'A road with<br>no finish line.', echappeeText:'On your indoor bike, a world unfolds ahead of you. Ride with your compatible smart trainer, follow a workout or simply explore in Contemplation mode.', echappeeStatus:'Available for Apple silicon Mac. iPhone and iPad coming later.',
  familyTitle:'A little less<br>to keep in mind.', familyText:'The next bag of milk, a first taste, the last wakeup. Four focused journals for the details of life with a baby.', familyCta:'Explore the family apps',
  catalog:'02 / The catalogue', catalogTitle:'What do you<br>want to make easier?', catalogIntro:'Browse by use, or find an app by name. Product pages explain the details and link to their available versions.', all:'All products', categories:{training:'Training & recovery',everyday:'Everyday life',family:'Baby & family',play:'Play & explore'}, search:'Find an app', placeholder:'Name or keyword…', clear:'Clear filters', results:'products', empty:'No app matches this search. Try another word or show all products.', site:'Product website', store:'App Store', availability:'Store pages show the current price and device compatibility.',
  closing:'A question about an app?', closingText:'Each product site has its own help and support contact. Choose the app to find the right place, along with its privacy policy and terms.', noTracking:'No cookies. No analytics.', top:'Back to top', theme:'Apps for your everyday life.'
 },
 fr: {
  title:'Des apps pour le quotidien — Benjamin Dupin', description:'Découvrez des apps pour le sport, les routines du quotidien, la vie avec bébé et le vélo en intérieur. Explorez leurs interfaces et trouvez celle qui vous convient.',
  skip:'Aller au contenu', nav:'Navigation principale', apps:'Applications', contact:'Aide & support', heroLabel:'Sport · Quotidien · Bébé & famille', hero:'Vos journées.<br><em>Vos compagnons.</em>', intro:'Garder le rythme à l’entraînement, retrouver les petits détails ou s’évader à vélo. Des apps à choisir selon ce qui compte dans votre journée.', heroCta:'Découvrir les applications', heroWork:'Explorer la sélection', heroNote:'Un minuteur. Un carnet d’énergie. Une route à explorer.',
  selected:'01 / Quelques produits', selectedTitle:'À chaque quotidien,<br>ses outils.', selectedIntro:'Pour la prochaine séance, une échappée au calme ou les petites logistiques de la vie de famille. Chaque produit part d’un besoin précis.',
  discover:'Découvrir', realShot:'Captures des produits', loadsenseCaption:'LoadSense · Vue de l’énergie du jour', familyCaption:'Petites Gouttes · Vue du stock de lait', echappeeCaption:'Échappée · Capture réelle du jeu · Graine 52025, km 8,3, 17 h 45',
  loadsenseTitle:'Lire son énergie.<br>Comprendre le contexte.', loadsenseText:'Sommeil, récupération et activité racontent chacun une partie de l’histoire. LoadSense les réunit, avec les données qui éclairent ses estimations.', loadsenseNote:'Des estimations pour votre information personnelle. Ce n’est pas un dispositif médical.',
  echappeeTitle:'Une route<br>sans ligne d’arrivée.', echappeeText:'Sur votre vélo d’intérieur, un monde se dessine devant vous. Roulez avec votre home trainer compatible, suivez une séance ou explorez simplement en mode Contemplation.', echappeeStatus:'Disponible sur Mac Apple silicon. iPhone et iPad viendront plus tard.',
  familyTitle:'Un peu moins<br>à garder en tête.', familyText:'Le prochain sachet de lait, une première saveur, le dernier réveil. Quatre carnets dédiés aux détails de la vie avec bébé.', familyCta:'Découvrir les apps pour la famille',
  catalog:'02 / Le catalogue', catalogTitle:'Qu’aimeriez-vous<br>rendre plus simple ?', catalogIntro:'Parcourez les usages ou retrouvez une app par son nom. Chaque site détaille le produit et renvoie vers ses versions disponibles.', all:'Tous les produits', categories:{training:'Sport & récupération',everyday:'Au quotidien',family:'Bébé & famille',play:'Jouer & explorer'}, search:'Trouver une application', placeholder:'Nom ou mot-clé…', clear:'Effacer les filtres', results:'produits', empty:'Aucune app ne correspond. Essayez un autre mot ou affichez tous les produits.', site:'Voir le site', store:'App Store', availability:'Les fiches des stores indiquent le prix et la compatibilité actuels.',
  closing:'Une question sur une app ?', closingText:'Chaque site produit propose son aide et son contact de support. Choisissez l’application pour retrouver le bon interlocuteur, sa confidentialité et ses conditions.', noTracking:'Sans cookies. Sans statistiques de visite.', top:'Haut de page', theme:'Des apps pour votre quotidien.'
 }
};
