// Public copy: shared product facts with explicit French and English wording.
// Do not turn code, a submission or a tag into a claim of store availability.
export const productCopy = {
 LoadSense: {category:'training', en:['iPhone · iPad · Apple Watch','Make sense of your daily energy.','A clearer view of energy, sleep and recovery from Apple Health, with the context behind the numbers.'], fr:['iPhone · iPad · Apple Watch','Comprendre son énergie du jour.','Une lecture de votre énergie, de votre sommeil et de votre récupération à partir d’Apple Santé, avec le contexte derrière les chiffres.']},
 TempoReps: {category:'training', en:['iPhone · Apple Watch','Keep your eyes on the next rep.','Timers for intervals, strength sessions and rest. Large, readable cues help you follow the workout.'], fr:['iPhone · Apple Watch','Garder le rythme, jusqu’à la dernière répétition.','Des minuteurs pour vos intervalles, vos séances de musculation et vos temps de repos. Des repères lisibles pour suivre l’effort.']},
 PRVault: {category:'training', en:['iPhone · iPad','Your next record starts with the last one.','Keep your lifting, WOD and cardio records together, and find your reference before the next session.'], fr:['iPhone · iPad','Le prochain record commence par le précédent.','Retrouvez vos records de musculation, de WOD et de cardio pour aborder la prochaine séance avec un repère.']},
 GrooveLog: {category:'training', en:['iPhone','Small sets. A regular practice.','A Grease the Groove journal that helps you build a routine around frequent, manageable sets.'], fr:['iPhone','De petites séries, une pratique régulière.','Un carnet Grease the Groove pour installer une routine de séries fréquentes et accessibles.']},
 ColdLoad: {category:'training', en:['iPhone','The right plates, without the maths.','Set the weight you want to lift and see how to load the bar with the plates you have.'], fr:['iPhone','Les bons disques, sans calcul mental.','Indiquez la charge visée et voyez comment monter votre barre avec les disques disponibles.']},
 MoveAtlas: {category:'training', en:['iPhone','Find a movement that fits.','Browse exercises and prepare a workout around your equipment, time and training focus.'], fr:['iPhone','Trouver le mouvement qui convient.','Explorez les exercices et préparez une séance selon votre matériel, votre temps et les zones à travailler.']},
 FastZen: {category:'everyday', en:['iPhone','A simple rhythm for fasting.','Preview your next seven days for free. With Custom Week, move a start or take a rest day for one date without changing your weekly routine.'], fr:['iPhone','Un rythme simple pour le jeûne.','Prévisualisez gratuitement les sept prochains jours. Avec la Semaine sur mesure, décalez un début ou prenez un jour de repos sans modifier votre semaine habituelle.']},
 NeatShift: {category:'everyday', en:['iPhone · iPad','Make room for a shared routine.','Organise household chores room by room, taking everyone’s availability into account.'], fr:['iPhone · iPad','Faire une place à chacun dans la routine.','Organisez les tâches de la maison pièce par pièce, en tenant compte des disponibilités de chacun.']},
 BrewMeter: {category:'everyday', en:['iPhone','Keep an eye on your caffeine.','Log your drinks and explore caffeine estimates in relation to the bedtime you choose.'], fr:['iPhone','Garder un œil sur sa caféine.','Notez vos boissons et consultez les estimations de caféine selon l’heure de coucher choisie.']},
 NoBuyCart: {category:'everyday', en:['iPhone','The pleasure of a cart. Without checkout.','Explore a fictional marketplace, fill a cart and keep track of what you chose not to spend.'], fr:['iPhone','Le plaisir du panier, sans passer en caisse.','Parcourez une boutique fictive, remplissez votre panier et visualisez ce que vous avez choisi de ne pas dépenser.']},
 PasDuJour: {category:'everyday', en:['Apple Watch','Your daily steps, at a glance.','Put a step count and a goal on your wrist, with complications and styles you can make your own.'], fr:['Apple Watch','Vos pas du jour, en un regard.','Retrouvez votre nombre de pas et votre objectif au poignet, avec des complications et des styles à personnaliser.']},
 'petites-gouttes': {category:'family', en:['iPhone','One less thing to remember.','Keep track of frozen breast milk, dates and the next bag to use. A practical companion for your stash.'], fr:['iPhone','Une chose de moins à retenir.','Retrouvez votre stock de lait maternel congelé, les dates et le prochain sachet à utiliser. Un repère concret au quotidien.']},
 'petites-bouchees': {category:'family', en:['iPhone','Remember every first taste.','Follow food introductions and record reactions in a journal you can return to as your baby discovers new flavours.'], fr:['iPhone','Se souvenir de chaque première bouchée.','Suivez les aliments introduits et notez les réactions dans un carnet à retrouver au fil des découvertes de bébé.']},
 'petites-nuits': {category:'family', en:['iPhone','A gentle record of little nights.','Note sleep, wakeups and feeds, then look back on your baby’s rhythm without relying on memory.'], fr:['iPhone','Un carnet doux pour les petites nuits.','Notez les périodes de sommeil, les réveils et les repas pour retrouver le rythme de bébé sans tout retenir.']},
 'petites-dents': {category:'family', en:['iPhone','Keep the story of every little tooth.','Record baby teeth as they arrive and keep their dates together in a timeline.'], fr:['iPhone','Garder l’histoire de chaque petite dent.','Notez l’arrivée des dents de lait et retrouvez leurs dates dans une chronologie.']},
 VesperDrift: {category:'play', en:['iPhone','One thumb. One more run.','A vertical arcade game of movement, timed attacks and a score to take a little further.'], fr:['iPhone','Un pouce. Encore une partie.','Un jeu d’arcade vertical où l’on se déplace, déclenche ses attaques au bon moment et pousse son score un peu plus loin.']},
 Echappee: {category:'play', en:['Apple silicon Mac','Turn the pedals. Let the road unfold.','A contemplative indoor cycling game with changing landscapes and a compatible FTMS smart trainer. iPhone and iPad versions are coming later.'], fr:['Mac Apple silicon','Tourner les jambes. Laisser la route venir.','Un jeu de cyclisme en intérieur contemplatif, des paysages changeants et un home trainer FTMS compatible. Les versions iPhone et iPad viendront plus tard.']},
};
