export const explorerCopy = {
  fr: {
    line1:'Votre prochaine', line2:'app préférée.',
    label:'17 applications indépendantes', edition:'Imaginées par Benjamin Dupin',
    intro:'Des apps pour bouger, jouer et simplifier le quotidien. À découvrir une carte à la fois.',
    shortIntro:'Explorez les apps. Gardez celles qui vous parlent.',
    chosen:'À découvrir', next:'Passer à une autre app', visit:'Voir le site',
    pass:'Passer', keep:'Garder', undo:'Annuler le dernier swipe',
    swipeHint:'Glissez la carte, ou utilisez les boutons.',
    keyboardHint:'Carte d’application. Glissez à gauche pour passer, à droite pour garder. Au clavier, utilisez les flèches gauche et droite lorsque la carte est sélectionnée.',
    deckLabel:'Explorer les applications', cardLabel:'Carte d’application',
    passStamp:'Une autre', keepStamp:'Pour moi', saved:'Dans ma sélection',
    selection:'Ma sélection', selectionTitle:'Celles qui<br>vous parlent.',
    selectionIntro:'Les apps que vous avez gardées, réunies au même endroit.',
    selectionEmpty:'Tout commence par un swipe.',
    selectionEmptyText:'Glissez une carte à droite, ou touchez le cœur pour garder une app ici.',
    selectionDevice:'Votre sélection reste dans ce navigateur.',
    selectionSession:'Votre sélection est disponible pour cette visite.',
    selectionCount:'app gardée', selectionCountPlural:'apps gardées',
    close:'Fermer la sélection', remove:'Retirer de ma sélection', save:'Garder dans ma sélection',
    kept:'ajoutée à votre sélection.', passed:'App suivante :', undone:'Retour à',
    failure:'Cette image ne se charge pas. Vous pouvez réessayer.',
    scroll:'La suite de la visite', pause:'Mettre les animations en pause', resume:'Activer les animations',
    all:'Tout le catalogue', chapter:'À chaque moment', chapterTitle:'Un autre rythme.\nUn autre horizon.',
  },
  en: {
    line1:'Your next', line2:'favourite app.',
    label:'17 independent applications', edition:'Made by Benjamin Dupin',
    intro:'Apps to move, play and simplify everyday life. Discover them one card at a time.',
    shortIntro:'Explore the apps. Keep the ones that speak to you.',
    chosen:'Discover', next:'Pass and see another app', visit:'Visit the site',
    pass:'Pass', keep:'Keep', undo:'Undo the last swipe',
    swipeHint:'Swipe the card, or use the buttons.',
    keyboardHint:'App card. Swipe left to pass, right to keep. With this card focused, use the left and right arrow keys.',
    deckLabel:'Explore the applications', cardLabel:'App card',
    passStamp:'Next one', keepStamp:'For me', saved:'In my selection',
    selection:'My selection', selectionTitle:'The ones that<br>speak to you.',
    selectionIntro:'The apps you kept, together in one place.',
    selectionEmpty:'It starts with a swipe.',
    selectionEmptyText:'Swipe a card right, or tap the heart to keep an app here.',
    selectionDevice:'Your selection stays in this browser.',
    selectionSession:'Your selection is available for this visit.',
    selectionCount:'app kept', selectionCountPlural:'apps kept',
    close:'Close selection', remove:'Remove from my selection', save:'Keep in my selection',
    kept:'added to your selection.', passed:'Next app:', undone:'Back to',
    failure:'This image could not load. You can try again.',
    scroll:'Continue the visit', pause:'Pause animations', resume:'Enable animations',
    all:'The full catalogue', chapter:'For every moment', chapterTitle:'Another rhythm.\nAnother horizon.',
  },
};
