export const studioCopy = {
 en: {
  title:'Apps by Benjamin Dupin',
  description:'Seventeen iOS apps by Benjamin Dupin. Training, household routines, baby journals, and two games.',
  skip:'Skip to content', nav:'Main navigation', languages:'Languages', apps:'Apps', guidesNav:'Guides',
  h1:'Seventeen apps',
  intro:'For iPhone, iPad, Mac, and Apple Watch.',
  all:'All',
  categories:{training:'Training', everyday:'Everyday', family:'Baby and family', play:'Games'},
  filterLabel:'Filter by use',
  search:'Search the apps', placeholder:'Name or word', clear:'Reset filters', results:'apps', singular:'app',
  empty:'No app matches.', emptyText:'Reset the filters to see all 17 apps.',
  guidesTitle:'Guides', guidesIntro:'Two guides already published on this site.',
  contactTitle:'Contact',
  contactFallback:'Without JavaScript, the support page already published for each app lists how to write.',
  contactText:'Use Contact. The message leaves from your mail app. This site does not send it.',
  supportDirectory:'Support page for each app',
  availability:'Prices and compatible devices are listed on the App Store.',
  store:'App Store', support:'Support', privacy:'Privacy policy', productSite:'Product site',
  shotCaption:'Screen from the published app.',
  privacyLead:'The privacy policy named on the App Store listing is published at the link below.',
  privacyMail:'Questions about that policy use Contact. This site does not send the message.',
  supportLead:'For a question about this app, use Contact. The message leaves from your mail app.',
  supportExisting:'The support page already published for this app is linked below.',
  footerLine:'iOS apps.', top:'Back to top', noTracking:'No cookies. No analytics.',
  homeLabel:'All apps'
 },
 fr: {
  title:'Applications de Benjamin Dupin',
  description:'Dix-sept applications iOS de Benjamin Dupin. Sport, routines de la maison, carnets de bébé, et deux jeux.',
  skip:'Aller au contenu', nav:'Navigation principale', languages:'Langues', apps:'Apps', guidesNav:'Guides',
  h1:'Dix-sept applications',
  intro:'Pour iPhone, iPad, Mac et Apple Watch.',
  all:'Toutes',
  categories:{training:'Sport', everyday:'Quotidien', family:'Bébé et famille', play:'Jeux'},
  filterLabel:'Filtrer par usage',
  search:'Rechercher une app', placeholder:'Nom ou mot', clear:'Effacer les filtres', results:'apps', singular:'app',
  empty:'Aucune app ne correspond.', emptyText:'Effacez les filtres pour revoir les 17 apps.',
  guidesTitle:'Guides', guidesIntro:'Deux guides déjà publiés sur ce site.',
  contactTitle:'Contact',
  contactFallback:'Sans JavaScript, la page de support déjà publiée pour chaque app indique comment écrire.',
  contactText:'Utilisez Contact. Le message part de votre application mail. Ce site ne l\'envoie pas.',
  supportDirectory:'Page de support de chaque app',
  availability:'Les prix et les appareils compatibles sont indiqués sur l\'App Store.',
  store:'App Store', support:'Support', privacy:'Politique de confidentialité', productSite:'Site du produit',
  shotCaption:'Écran de l\'application publiée.',
  privacyLead:'La politique de confidentialité indiquée sur la fiche App Store est publiée à l\'adresse ci-dessous.',
  privacyMail:'Les questions sur cette politique passent par Contact. Ce site n\'envoie pas le message.',
  supportLead:'Pour une question sur cette app, utilisez Contact. Le message part de votre application mail.',
  supportExisting:'La page de support déjà publiée pour cette app est liée ci-dessous.',
  footerLine:'Applications iOS.', top:'Retour en haut', noTracking:'Sans cookies. Sans analytics.',
  homeLabel:'Toutes les apps'
 }
};
