export const studioCopy = {
 en: {
  title:'Small apps. For real life. — Benjamin Dupin', description:'17 independent apps by Benjamin Dupin. For your next workout, the little things at home, life with a baby, and a moment to escape.',
  skip:'Skip to content',nav:'Main navigation',apps:'The apps',selected:'In the spotlight',support:'App support',languages:'Languages',identity:'Independent apps',
  eyebrow:'Independent apps, by Benjamin Dupin',hero:'What brings<br>you here?',intro:'Prepare a workout, keep a family journal, make a routine simpler. Find the app for what you want to do.',explore:'Find your app',heroNote:'For iPhone, iPad, Mac & Apple Watch',artNote:'A little help.<br>A lot of possibilities.',artLabel:'A closer look at LoadSense and Petites Bouchées',
  selectedLabel:'A closer look',selectedTitle:'Three ways to begin.',selectedIntro:'A change of scenery, training data, or a family journal.',
  roadKicker:'Échappée · Indoor cycling',roadTitle:'A change<br>of scenery.',roadText:'Turn the pedals. Watch the world unfold. Explore changing landscapes with your compatible smart trainer.',roadCta:'Take the scenic route',roadStatus:'Available for Apple silicon Mac. iPhone and iPad coming later.',roadAlt:'Échappée game capture: a sunlit mountain road winding towards a pass',roadCaption:'Real game capture · Seed 52025 · km 8.3 · 17:45',
  energyKicker:'LoadSense · Training & recovery',energyTitle:'Read your days<br>with context.',energyText:'Energy, sleep and recovery, with the context behind the numbers.',energyCta:'Meet LoadSense',energyNote:'Personal health estimates. Not a medical device.',
  familyKicker:'The Petites family · 4 apps',familyTitle:'Little moments.<br>Less to remember.',familyText:'First tastes, little nights, milk supplies and new teeth. A journal for each new chapter.',familyCta:'Meet the family',
  guideLabel:'Choose an everyday use',categoryNotes:{training:'Plan, time and keep track of training',everyday:'Caffeine, chores, steps and spending wishes',family:'Milk, first tastes, sleep and little teeth',play:'A quick run or a longer escape'},catalogLabel:'The catalogue / 17 apps',catalogTitle:'Find your app.',catalogIntro:'Real screens, a clear purpose. Explore a product before opening the store.',all:'All apps',categories:{training:'Training',everyday:'Everyday life',family:'Baby & family',play:'Play & escape'},
  search:'Search the apps',placeholder:'An app, a need…',clear:'Reset filters',results:'apps',singular:'app',empty:'No apps here just yet.',emptyText:'Try another word or reset the filters to see all 17 apps.',site:'Discover',availability:'Current prices and device compatibility are listed on the App Store.',
  supportLabel:'A helping hand',supportTitle:'Help with your app.',supportText:'Need help with an app? Its website has the answers, support contact and privacy information.',supportSelect:'Choose your app',supportCta:'Visit app support',supportPlaceholder:'Select an app',
  footerLine:'Small apps. For real life.',top:'Back to top',noTracking:'No cookies. No analytics.'
 },
 fr: {
  title:'Des apps. Pour la vraie vie. — Benjamin Dupin',description:'17 applications indépendantes par Benjamin Dupin. Pour la prochaine séance, les petites choses de la maison, la vie avec bébé et les envies d’évasion.',
  skip:'Aller au contenu',nav:'Navigation principale',apps:'Les apps',selected:'À découvrir',support:'Aide & support',languages:'Langues',identity:'Apps indépendantes',
  eyebrow:'Applications indépendantes, par Benjamin Dupin',hero:'Quel usage<br>vous amène ?',intro:'Préparer une séance, garder un carnet de famille, simplifier une routine. Trouvez l’app pour ce que vous voulez faire.',explore:'Trouver votre app',heroNote:'Pour iPhone, iPad, Mac et Apple Watch',artNote:'Un petit coup de main.<br>Plein de possibilités.',artLabel:'Aperçu de LoadSense et de Petites Bouchées',
  selectedLabel:'Pour aller plus loin',selectedTitle:'Trois points de départ.',selectedIntro:'Changer de paysage, lire ses données sportives ou garder un carnet de famille.',
  roadKicker:'Échappée · Vélo en intérieur',roadTitle:'Changer<br>d’horizon.',roadText:'Tournez les jambes. Laissez le paysage défiler. Explorez un monde changeant avec votre home trainer compatible.',roadCta:'Prendre la route',roadStatus:'Disponible sur Mac Apple silicon. iPhone et iPad viendront plus tard.',roadAlt:'Capture du jeu Échappée : une route de montagne ensoleillée serpente vers un col',roadCaption:'Capture réelle du jeu · Graine 52025 · km 8,3 · 17 h 45',
  energyKicker:'LoadSense · Sport & récupération',energyTitle:'Vos journées,<br>avec du contexte.',energyText:'Énergie, sommeil et récupération, avec le contexte derrière les chiffres.',energyCta:'Découvrir LoadSense',energyNote:'Estimations personnelles de santé. Ceci n’est pas un dispositif médical.',
  familyKicker:'La famille Petites · 4 apps',familyTitle:'Petits moments.<br>Moins à retenir.',familyText:'Premières bouchées, petites nuits, réserves de lait et nouvelles dents. Un carnet pour chaque découverte.',familyCta:'Rencontrer la famille',
  guideLabel:'Choisir un usage',categoryNotes:{training:'Préparer, rythmer et suivre ses séances',everyday:'Caféine, ménage, pas et envies d’achat',family:'Lait, premiers goûts, sommeil et petites dents',play:'Une partie ou une longue échappée'},catalogLabel:'Le catalogue / 17 apps',catalogTitle:'Trouvez votre app.',catalogIntro:'De vrais écrans, un usage précis. Découvrez un produit avant d’ouvrir le store.',all:'Toutes les apps',categories:{training:'Sport',everyday:'Quotidien',family:'Bébé & famille',play:'Jeux & évasion'},
  search:'Rechercher une app',placeholder:'Une app, un besoin…',clear:'Effacer les filtres',results:'apps',singular:'app',empty:'Aucune app pour cette recherche.',emptyText:'Essayez un autre mot ou effacez les filtres pour retrouver les 17 apps.',site:'Découvrir',availability:'Les tarifs et les appareils compatibles sont indiqués sur l’App Store.',
  supportLabel:'Un coup de main',supportTitle:'L’aide de votre app.',supportText:'Besoin d’aide avec une app ? Son site réunit les réponses, le contact support et les informations de confidentialité.',supportSelect:'Choisir votre app',supportCta:'Accéder à l’aide',supportPlaceholder:'Sélectionner une app',
  footerLine:'Des apps. Pour la vraie vie.',top:'Retour en haut',noTracking:'Sans cookies. Sans analytics.'
 }
};
