export const studioCopy = {
 en: {
  title:'Small apps. For real life. — Benjamin Dupin', description:'17 independent apps by Benjamin Dupin. For your next workout, the little things at home, life with a baby, and a moment to escape.',
  skip:'Skip to content',nav:'Main navigation',apps:'The apps',selected:'In the spotlight',support:'App support',languages:'Languages',identity:'Independent apps',
  eyebrow:'Independent apps, by Benjamin Dupin',hero:'Small apps.<br>For <em>real life.</em>',intro:'A workout. A first taste. A little escape. Apps for the things that make a day yours.',explore:'Find your app',heroNote:'For iPhone, iPad, Mac & Apple Watch',artNote:'A little help.<br>A lot of possibilities.',artLabel:'A closer look at LoadSense and Petites Bouchées',
  selectedLabel:'01 / In the spotlight',selectedTitle:'Different apps.<br>The same attention.',selectedIntro:'A few ways to make room for what matters to you.',
  roadKicker:'Échappée · Indoor cycling',roadTitle:'A change<br>of scenery.',roadText:'Turn the pedals. Watch the world unfold. Explore changing landscapes with your compatible smart trainer.',roadCta:'Take the scenic route',roadStatus:'Available for Apple silicon Mac. iPhone and iPad coming later.',roadAlt:'Échappée game capture: a sunlit mountain road winding towards a pass',roadCaption:'Real game capture · Seed 52025 · km 8.3 · 17:45',
  energyKicker:'LoadSense · Training & recovery',energyTitle:'How are you,<br>really?',energyText:'Energy, sleep and recovery, with the context behind the numbers.',energyCta:'Meet LoadSense',energyNote:'Personal health estimates. Not a medical device.',
  familyKicker:'The Petites family · 4 apps',familyTitle:'Little moments.<br>Less to remember.',familyText:'First tastes, little nights, milk supplies and new teeth. A journal for each new chapter.',familyCta:'Meet the family',
  catalogLabel:'02 / The collection',catalogTitle:'There’s a little<br>something for you.',catalogIntro:'Pick a part of your day. Find an app to go with it.',all:'All apps',categories:{training:'Training',everyday:'Everyday life',family:'Baby & family',play:'Play & escape'},
  search:'Search the apps',placeholder:'An app, a need…',clear:'Reset filters',results:'apps',singular:'app',empty:'No apps here just yet.',emptyText:'Try another word or reset the filters to see all 17 apps.',site:'Discover',availability:'Current prices and device compatibility are listed on the App Store.',
  supportLabel:'A helping hand',supportTitle:'Let’s find<br>the right answer.',supportText:'Need help with an app? Its website has the answers, support contact and privacy information.',supportSelect:'Choose your app',supportCta:'Visit app support',supportPlaceholder:'Select an app',
  footerLine:'Small apps. For real life.',top:'Back to top',noTracking:'No cookies. No analytics.'
 },
 fr: {
  title:'Des apps. Pour la vraie vie. — Benjamin Dupin',description:'17 applications indépendantes par Benjamin Dupin. Pour la prochaine séance, les petites choses de la maison, la vie avec bébé et les envies d’évasion.',
  skip:'Aller au contenu',nav:'Navigation principale',apps:'Les apps',selected:'À découvrir',support:'Aide & support',languages:'Langues',identity:'Apps indépendantes',
  eyebrow:'Applications indépendantes, par Benjamin Dupin',hero:'Des apps.<br>Pour la <em>vraie vie.</em>',intro:'Une séance. Une première bouchée. Une échappée. Des apps pour tout ce qui fait votre journée.',explore:'Trouver votre app',heroNote:'Pour iPhone, iPad, Mac et Apple Watch',artNote:'Un petit coup de main.<br>Plein de possibilités.',artLabel:'Aperçu de LoadSense et de Petites Bouchées',
  selectedLabel:'01 / À découvrir',selectedTitle:'Des apps différentes.<br>Le même soin.',selectedIntro:'Quelques façons de faire une place à ce qui compte pour vous.',
  roadKicker:'Échappée · Vélo en intérieur',roadTitle:'Changer<br>d’horizon.',roadText:'Tournez les jambes. Laissez le paysage défiler. Explorez un monde changeant avec votre home trainer compatible.',roadCta:'Prendre la route',roadStatus:'Disponible sur Mac Apple silicon. iPhone et iPad viendront plus tard.',roadAlt:'Capture du jeu Échappée : une route de montagne ensoleillée serpente vers un col',roadCaption:'Capture réelle du jeu · Graine 52025 · km 8,3 · 17 h 45',
  energyKicker:'LoadSense · Sport & récupération',energyTitle:'Comment<br>ça va, vraiment ?',energyText:'Énergie, sommeil et récupération, avec le contexte derrière les chiffres.',energyCta:'Découvrir LoadSense',energyNote:'Estimations personnelles de santé. Ceci n’est pas un dispositif médical.',
  familyKicker:'La famille Petites · 4 apps',familyTitle:'Petits moments.<br>Moins à retenir.',familyText:'Premières bouchées, petites nuits, réserves de lait et nouvelles dents. Un carnet pour chaque découverte.',familyCta:'Rencontrer la famille',
  catalogLabel:'02 / La collection',catalogTitle:'Une petite place<br>dans votre quotidien.',catalogIntro:'Choisissez un moment de votre journée. Trouvez l’app qui va avec.',all:'Toutes les apps',categories:{training:'Sport',everyday:'Quotidien',family:'Bébé & famille',play:'Jeux & évasion'},
  search:'Rechercher une app',placeholder:'Une app, un besoin…',clear:'Effacer les filtres',results:'apps',singular:'app',empty:'Aucune app pour cette recherche.',emptyText:'Essayez un autre mot ou effacez les filtres pour retrouver les 17 apps.',site:'Découvrir',availability:'Les tarifs et les appareils compatibles sont indiqués sur l’App Store.',
  supportLabel:'Un coup de main',supportTitle:'Trouvons<br>la bonne réponse.',supportText:'Besoin d’aide avec une app ? Son site réunit les réponses, le contact support et les informations de confidentialité.',supportSelect:'Choisir votre app',supportCta:'Accéder à l’aide',supportPlaceholder:'Sélectionner une app',
  footerLine:'Des apps. Pour la vraie vie.',top:'Retour en haut',noTracking:'Sans cookies. Sans analytics.'
 }
};
