import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {copy,productCopy} from '../content/copy.mjs';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const apps=JSON.parse(await readFile(resolve(root,'content/catalog.json'),'utf8'));
const profile=JSON.parse(await readFile(resolve(root,'content/profile.json'),'utf8'));
const origin='https://bnjdpn.github.io';
const assetVersions=new Map(await Promise.all(['styles.css','assets/experience.css','assets/product-media.css','assets/site.js','assets/experience.mjs'].map(async path=>[path,createHash('sha256').update(await readFile(resolve(root,path))).digest('hex').slice(0,12)])));
const assetUrl=path=>`/${path}?v=${assetVersions.get(path)}`;
const previewMedia=JSON.parse(await readFile(resolve(root,'content/preview-media.json'),'utf8'));
for (const locales of Object.values(previewMedia)) for (const m of Object.values(locales)) {
 const [x,y,w,h]=m.frame||[0,0,1,1];
 if (![x,y,w,h].every(Number.isFinite)||x<0||y<0||w<=0||h<=0||x+w>1.000001||y+h>1.000001) throw new Error(`Invalid public image frame: ${m.src}`);
 if (m.catalogOffset!==undefined&&(!Number.isFinite(m.catalogOffset)||m.catalogOffset<0)) throw new Error(`Invalid catalogue focal point: ${m.src}`);
}
const mediaStyle=m=>{const [x,y,w,h]=m.frame||[0,0,1,1];return `--screen-ratio:${m.width*w/(m.height*h)};--screen-width:${100/w}%;--screen-left:${-100*x/w}%;--screen-top:${-100*y/h}%;--catalog-offset:${m.catalogOffset||0}`};
const screen=(m,alt,attrs='')=>`<span class="screen-viewport" style="${mediaStyle(m)}"><img src="${m.src}" width="${m.width}" height="${m.height}" alt="${esc(alt)}" ${attrs} decoding="async"></span>`;
const preview=(a,lang)=>{const m=previewMedia[a.path][lang];return `<a class="product-preview" href="${publicUrl(a,lang)}" aria-label="${esc(a.name)}">${screen(m,a.name,'loading="lazy"')}</a>`};
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const publicUrl=(a,lang)=>`${origin}/${a.path}/${lang==='fr'?'fr-FR/' : ''}`;
// French paths follow each product site's existing published routing.
const icon=a=>`<img class="app-icon" src="/assets/apps/${a.icon}.${a.iconFormat||'webp'}" width="512" height="512" alt="" loading="lazy" decoding="async">`;
const shot=(name,lang,alt)=>screen(previewMedia[apps.find(a=>a.icon===name).path][lang],alt,'loading="lazy"');
const outputs=new Map();
for(const lang of ['en','fr']) {
 const t=copy[lang], url=origin+(lang==='fr'?'/fr/':'/');
 const app=path=>apps.find(a=>a.path===path);
 const discovery=apps.map((a,i)=>({id:a.path,name:a.name,number:String(i+1).padStart(2,'0'),url:publicUrl(a,lang),category:productCopy[a.path].category,categoryLabel:t.categories[productCopy[a.path].category],platform:productCopy[a.path][lang][0],headline:productCopy[a.path][lang][1],description:productCopy[a.path][lang][2],image:(({src,width,height,frame})=>({src,width,height,frame}))(previewMedia[a.path][lang]),icon:`/assets/apps/${a.icon}.${a.iconFormat||'webp'}`}));
 const lead=discovery[0];
 const d=lang==='fr'?{line1:'Le quotidien,',line2:'autrement.',label:'17 apps indépendantes. Autant de possibles.',chosen:'À découvrir cette fois',next:'Une autre découverte',scroll:'Faites défiler pour explorer',pause:'Mettre les animations en pause',resume:'Activer les animations',all:'Les 17 applications',chapter:'Changer de perspective',chapterTitle:'Un autre rythme.\nUn autre horizon.'}:{line1:'Everyday life,',line2:'reimagined.',label:'17 independent apps. So many possibilities.',chosen:'This time, discover',next:'Discover another app',scroll:'Scroll to explore',pause:'Pause animations',resume:'Enable animations',all:'All 17 applications',chapter:'A change of perspective',chapterTitle:'Another rhythm.\nAnother horizon.'};
 const graph=[profile,{'@type':'WebSite','@id':`${origin}/#website`,url:origin+'/',name:'Benjamin Dupin',inLanguage:['en','fr'],publisher:{'@id':profile['@id']}},{'@type':'CollectionPage','@id':url+'#apps',url,name:t.title,description:t.description,inLanguage:lang,dateModified:'2026-09-07T12:00:00Z',mainEntity:{'@id':url+'#catalogue'}},{'@type':'ItemList','@id':url+'#catalogue',name:t.apps,numberOfItems:apps.length,itemListElement:apps.map((a,i)=>({'@type':'ListItem',position:i+1,name:a.name,url:publicUrl(a,lang)}))}];
 const catalog=apps.map((a,i)=>{ const c=productCopy[a.path], [platform,headline,desc]=c[lang]; return `<article class="product-row" data-app="${a.path}" data-category="${c.category}" data-search="${esc(a.name+' '+headline+' '+desc)}">${preview(a,lang)}<div class="product-identity">${icon(a)}<div><p class="product-state">${esc(platform)}</p><h3>${esc(a.name)}</h3></div></div><div class="product-copy"><p class="product-headline">${esc(headline)}</p><p>${esc(desc)}</p></div><div class="product-actions"><a href="${publicUrl(a,lang)}" aria-label="${esc(t.site+' · '+a.name)}">${t.site} <span aria-hidden="true">↗</span></a>${`<a class="store-link" href="https://apps.apple.com/app/id${a.id}${a.path==='Echappee'?'?mt=12':''}" aria-label="App Store · ${esc(a.name)}">App Store <span aria-hidden="true">↗</span></a>`}</div></article>`}).join('\n');
 outputs.set(lang==='en'?'index.html':'fr/index.html',`<!doctype html>
<!-- Generated by scripts/build-site.mjs. Edit content/ and the generator, not this output. -->
<html lang="${lang}"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(t.title)}</title><meta name="description" content="${esc(t.description)}">
<meta name="google-site-verification" content="Bs6cO9WFohARbIFhvij399ZDgCetytfajAwoCQHBB48">
<meta name="theme-color" content="#090c10"><meta name="robots" content="index, follow, max-image-preview:large">
<link rel="canonical" href="${url}"><link rel="alternate" hreflang="en" href="${origin}/"><link rel="alternate" hreflang="fr" href="${origin}/fr/"><link rel="alternate" hreflang="x-default" href="${origin}/">
<link rel="icon" href="/assets/profile/github-avatar.jpg" type="image/jpeg"><link rel="apple-touch-icon" href="/assets/profile/github-avatar.jpg"><link rel="manifest" href="/site.webmanifest"><link rel="preload" href="/assets/fonts/space-grotesk-latin.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="${assetUrl('styles.css')}"><link rel="stylesheet" href="${assetUrl('assets/experience.css')}"><link rel="stylesheet" href="${assetUrl('assets/product-media.css')}">
<meta property="og:type" content="website"><meta property="og:locale" content="${lang==='fr'?'fr_FR':'en_US'}"><meta property="og:locale:alternate" content="${lang==='fr'?'en_US':'fr_FR'}"><meta property="og:site_name" content="Benjamin Dupin"><meta property="og:title" content="${esc(t.title)}"><meta property="og:description" content="${esc(t.description)}"><meta property="og:url" content="${url}"><meta property="og:image" content="${origin}/assets/social/og.jpg"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="Benjamin Dupin · ${esc(t.theme)}">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(t.title)}"><meta name="twitter:description" content="${esc(t.description)}"><meta name="twitter:image" content="${origin}/assets/social/og.jpg">
<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@graph':graph},null,2)}</script>
<script src="${assetUrl('assets/site.js')}" defer></script><script type="module" src="${assetUrl('assets/experience.mjs')}"></script><script type="application/json" id="discovery-data">${JSON.stringify(discovery).replaceAll('<','\\u003c')}</script></head><body id="top"><div class="reading-progress" aria-hidden="true"></div>
<a class="skip-link" href="#main">${t.skip}</a>
<header class="masthead"><a class="identity" href="${lang==='fr'?'/fr/':'/'}"><span class="monogram" aria-hidden="true">bd.</span><span>Benjamin Dupin</span></a><nav aria-label="${t.nav}"><a href="#products">${t.apps}</a><a class="nav-contact" href="#contact">${t.contact} <span aria-hidden="true">↗</span></a></nav><nav class="languages" aria-label="${lang==='fr'?'Langues':'Languages'}"><a href="/fr/" lang="fr" hreflang="fr" ${lang==='fr'?'aria-current="page"':''}>FR</a><span aria-hidden="true">/</span><a href="/" lang="en" hreflang="en" ${lang==='en'?'aria-current="page"':''}>EN</a></nav></header>
<main id="main" tabindex="-1">
<section class="hero experience" id="about" aria-labelledby="hero-title" data-featured="${lead.id}">
<div class="experience-stage">
<canvas class="flow-field" aria-hidden="true"></canvas><div class="stage-grid" aria-hidden="true"></div>
<div class="experience-topline"><p class="eyebrow">${d.label}</p><span class="edition-mark" aria-hidden="true">BD / APPS — 2026</span></div>
<div class="hero-heading"><h1 id="hero-title"><span>${d.line1}</span><em>${d.line2}</em></h1><p class="hero-subtitle">${t.intro}</p></div>
<figure class="discovery-visual" style="${mediaStyle(lead.image)}"><a id="discovery-image-link" href="${lead.url}" aria-label="${esc(t.discover+' '+lead.name)}">${screen(lead.image,lead.name,'id="discovery-image" fetchpriority="high"')}</a><figcaption><span id="visual-app-name">${esc(lead.name)}</span><span class="visual-caption">${lang==='fr'?'Vue du produit':'Product view'}</span></figcaption></figure>
<div class="discovery-copy"><p class="discovery-kicker"><span class="live-dot" aria-hidden="true"></span>${d.chosen} <span id="discovery-number">${lead.number}</span><span class="dim">/ 17</span></p><div class="discovery-identity"><img id="discovery-icon" src="${lead.icon}" width="48" height="48" alt=""><h2 id="discovery-name">${esc(lead.name)}</h2></div><p id="discovery-headline">${esc(lead.headline)}</p><p id="discovery-platform">${esc(lead.platform)}</p><div class="discovery-actions"><a class="button" id="discovery-link" href="${lead.url}">${t.discover} <span aria-hidden="true">↗</span></a><button type="button" id="next-discovery" class="shuffle-button" hidden aria-label="${d.next}" title="${d.next}"><span aria-hidden="true">↻</span></button></div><p class="sr-only" id="discovery-announcement" role="status" aria-live="polite"></p></div>
<div class="experience-bottom"><a href="#selected" class="scroll-cue"><span class="scroll-track" aria-hidden="true"><i></i></span>${d.scroll}</a><a href="#products" class="all-apps-link">${d.all} <span aria-hidden="true">↗</span></a><button class="motion-toggle" id="motion-toggle" type="button" aria-pressed="false" aria-label="${d.pause}" data-pause="${d.pause}" data-resume="${d.resume}" hidden><span aria-hidden="true">Ⅱ</span></button></div>
</div></section>
<div class="story-intro" data-reveal><p class="eyebrow">${d.chapter}</p><p class="story-statement">${d.chapterTitle.split('\n').map((line,i)=>`<span ${i?'class="statement-outline"':''}>${line}</span>`).join('')}</p><span class="story-arrow" aria-hidden="true">↘</span></div>
<section id="selected" class="selected" aria-labelledby="selected-title"><header class="section-heading"><p class="eyebrow">${t.selected}</p><h2 id="selected-title">${t.selectedTitle}</h2><p>${t.selectedIntro}</p></header>
<article class="feature feature-energy" data-scene="01"><span class="scene-number" aria-hidden="true">01 / 03</span><div class="feature-copy"><p class="eyebrow">LoadSense / ${t.categories.training}</p><h3>${t.loadsenseTitle}</h3><p>${t.loadsenseText}</p><a class="button button-light" href="${publicUrl(app('LoadSense'),lang)}">${t.discover} LoadSense <span aria-hidden="true">↗</span></a><small>${t.loadsenseNote}</small></div><figure>${shot('loadsense',lang,t.loadsenseCaption)}<figcaption>${t.loadsenseCaption}</figcaption></figure></article>
<article class="feature feature-road" data-scene="02"><span class="scene-number" aria-hidden="true">02 / 03</span><figure><img src="/assets/previews/echappee.webp" width="1520" height="950" alt="${lang==='fr'?'Capture du jeu Échappée : la route monte vers un col au soleil couchant':'Échappée game capture: the road climbs towards a pass in the evening sun'}" loading="lazy" decoding="async"><figcaption>${t.echappeeCaption}</figcaption></figure><div class="road-copy"><div><p class="eyebrow">Échappée / ${t.categories.play}</p><h3>${t.echappeeTitle}</h3></div><div><p>${t.echappeeText}</p><a class="text-link" href="${publicUrl(app('Echappee'),lang)}">${t.discover} Échappée <span aria-hidden="true">↗</span></a><small>${t.echappeeStatus}</small></div></div></article>
<article class="feature feature-family" data-scene="03"><span class="scene-number" aria-hidden="true">03 / 03</span><div class="feature-copy"><p class="eyebrow">${t.categories.family}</p><h3>${t.familyTitle}</h3><p>${t.familyText}</p><div class="family-icons">${apps.filter(a=>a.path.startsWith('petites-')).map(a=>`<a href="${publicUrl(a,lang)}" aria-label="${a.name}">${icon(a)}</a>`).join('')}</div><a class="text-link" href="#products" data-category-link="family">${t.familyCta} <span aria-hidden="true">↗</span></a></div><figure>${shot('petites-gouttes',lang,t.familyCaption)}<figcaption>${t.familyCaption}</figcaption></figure></article>
</section>
<section class="catalog" data-reveal id="products" aria-labelledby="products-title"><header class="section-heading"><p class="eyebrow">${t.catalog}</p><h2 id="products-title">${t.catalogTitle}</h2><p>${t.catalogIntro}</p></header><div class="catalog-tools" hidden><div class="filters" role="group" aria-label="${lang==='fr'?'Filtrer par usage':'Filter by use'}"><button type="button" data-filter="all" aria-pressed="true">${t.all}</button>${Object.entries(t.categories).map(([k,v])=>`<button type="button" data-filter="${k}" aria-pressed="false">${v}</button>`).join('')}</div><label class="search">${t.search}<input type="search" placeholder="${t.placeholder}" id="app-search" autocomplete="off"></label></div><div class="catalog-summary" hidden><p role="status" aria-live="polite" id="result-count" data-label="${t.results}" data-singular="${lang==='fr'?'produit':'product'}">${apps.length} ${t.results}</p><button type="button" id="clear-filters">${t.clear}</button></div><div class="product-index" id="product-index">${catalog}</div><p id="no-results" hidden>${t.empty}</p><p class="availability-note">${t.availability}</p></section>
<section class="contact" data-reveal id="contact" aria-labelledby="contact-title"><div><p class="eyebrow">${t.contact}</p><h2 id="contact-title">${t.closing}</h2><p>${t.closingText}</p></div><ul class="support-index">${apps.map(a=>`<li><a href="${publicUrl(a,lang)}${a.path==='Echappee'?'support.html':'#contact'}">${esc(a.name)} <span aria-hidden="true">↗</span></a></li>`).join('')}</ul></section>
</main><footer class="footer"><p>© 2026 Benjamin Dupin</p><p>${t.noTracking}</p><a href="#top">${t.top} ↑</a></footer></body></html>\n`);
}
outputs.set('sitemap-pages.xml',`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n${['','fr/'].map(path=>`<url><loc>${origin}/${path}</loc><xhtml:link rel="alternate" hreflang="en" href="${origin}/"/><xhtml:link rel="alternate" hreflang="fr" href="${origin}/fr/"/></url>`).join('\n')}\n</urlset>\n`);
outputs.set('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?>\n<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n<sitemap><loc>${origin}/sitemap-pages.xml</loc></sitemap>\n${apps.map(a=>`<sitemap><loc>${origin}/${a.path}/sitemap.xml</loc></sitemap>`).join('\n')}\n</sitemapindex>\n`);
let stale=false;
for(const [path,html] of outputs) { if(process.argv.includes('--check')) {const current=await readFile(resolve(root,path),'utf8').catch(()=>null); if(current!==html){console.error(`Stale generated output: ${path}. Run npm run build.`);stale=true;}}else{await mkdir(dirname(resolve(root,path)),{recursive:true});await writeFile(resolve(root,path),html);}}
if(stale)process.exit(1);
console.log(`✓ ${outputs.size} static outputs ${process.argv.includes('--check')?'are current':'generated'} (English + French, ${apps.length} products)`);
