import {access,readFile,readdir} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const catalog=JSON.parse(await readFile(resolve(root,'content/catalog.json'),'utf8'));
const styles=(await Promise.all(['styles.css','assets/experience.css'].map(path=>readFile(resolve(root,path),'utf8')))).join('\n');
const workflow=await readFile(resolve(root,'.github/workflows/pages.yml'),'utf8');
const sitemap=await readFile(resolve(root,'sitemap.xml'),'utf8');
const pages=await readFile(resolve(root,'sitemap-pages.xml'),'utf8');
const failures=[]; let references=0;
const expect=(value,msg)=>{if(!value)failures.push(msg)};
for(const [path,lang] of [['index.html','en'],['fr/index.html','fr']]) {
 const html=await readFile(resolve(root,path),'utf8');
 const prefix=`${path}: `;
 expect(html.includes(`<html lang="${lang}">`),prefix+'wrong document language');
 expect((html.match(/<h1\b/g)||[]).length===1,prefix+'one H1 required');
 for(const id of ['main','about','selected','products','contact']) expect(html.includes(`id="${id}"`),prefix+`missing #${id}`);
 expect(html.includes('<a class="skip-link" href="#main">'),prefix+'skip link missing');
 expect(html.includes('Bs6cO9WFohARbIFhvij399ZDgCetytfajAwoCQHBB48'),prefix+'Search Console verification missing');
 expect(html.includes(`rel="canonical" href="https://bnjdpn.github.io/${lang==='fr'?'fr/':''}"`),prefix+'canonical mismatch');
 for(const l of ['fr','en','x-default'])expect(html.includes(`hreflang="${l}"`),prefix+`hreflang ${l} missing`);
 const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
 expect(new Set(ids).size===ids.length,prefix+'duplicate IDs');
 for(const match of html.matchAll(/href="#([^"]+)"/g))expect(ids.includes(match[1]),prefix+'broken anchor '+match[1]);
 const rows=[...html.matchAll(/<article class="product-row"[\s\S]*?<\/article>/g)].map(m=>m[0]);
 expect(rows.length===catalog.length,prefix+'catalogue length mismatch');
 expect(rows.every(row=>row.includes('data-category=')&&row.includes('data-search=')),prefix+'uncategorized product');
 const storeIds=new Set([...html.matchAll(/apps\.apple\.com\/app\/id(\d+)/g)].map(m=>m[1]));
 const expectedIds=catalog.filter(a=>a.id).map(a=>a.id);
 expect(storeIds.size===expectedIds.length && expectedIds.every(id=>storeIds.has(id)),prefix+'store destinations drifted');
 expect(!html.includes('NovaStationPinball')&&!html.includes('6799920176'),prefix+'retired app reintroduced');
 expect(html.includes(lang==='fr'?'iPhone et iPad viendront plus tard':'iPhone and iPad coming later'),prefix+'Echappee platform caveat missing');
 const graph=JSON.parse(html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/)[1])['@graph'];
 for(const type of ['Person','WebSite','CollectionPage','ItemList'])expect(graph.some(x=>x['@type']===type),prefix+'missing JSON-LD '+type);
 const list=graph.find(x=>x['@type']==='ItemList');
 expect(list.numberOfItems===catalog.length&&list.itemListElement.length===catalog.length,prefix+'structured catalogue count mismatch');
 expect(!JSON.stringify(graph).includes('"offers"'),prefix+'unverified offer in JSON-LD');
 expect(/^\d{4}-\d{2}-\d{2}T.*Z$/.test(graph.find(x=>x['@type']==='CollectionPage').dateModified),prefix+'invalid modification timestamp');
 expect(!/mailto:|target="_blank"/.test(html),prefix+'direct email or forced new tabs');
 for(const img of html.matchAll(/<img\b[^>]+>/g)) expect(/\bwidth="\d+"/.test(img[0])&&/\bheight="\d+"/.test(img[0])&&/\balt="[^"]*"/.test(img[0]),prefix+'image lacks dimensions/alt');
 const refs=new Set([...html.matchAll(/(?:href|src)="([^"#]+)"/g)].map(m=>m[1]).filter(ref=>!/^https?:|^data:/.test(ref)));
 for(let ref of refs){ref=ref.replace(/^\//,'').split('?')[0];if(ref===''||ref.endsWith('/'))ref+='index.html';try{await access(resolve(root,ref));references++;}catch{failures.push(prefix+'missing file '+ref);}}
 expect(html.includes('class="catalog-tools" hidden'),prefix+'filters must be progressive enhancement');
}
expect(sitemap.match(/<sitemap>/g)?.length===catalog.length+1,'sitemap index count mismatch');
for(const app of catalog)expect(sitemap.includes(`https://bnjdpn.github.io/${app.path}/sitemap.xml`),'missing product sitemap '+app.path);
for(const url of ['https://bnjdpn.github.io/','https://bnjdpn.github.io/fr/'])expect(pages.includes(`<loc>${url}</loc>`),'missing page sitemap '+url);
expect((await readFile(resolve(root,'robots.txt'),'utf8')).includes('Sitemap: https://bnjdpn.github.io/sitemap.xml'),'robots sitemap missing');
expect((await readFile(resolve(root,'404.html'),'utf8')).includes('noindex'),'404 must be noindex');
JSON.parse(await readFile(resolve(root,'site.webmanifest'),'utf8'));
expect(styles.includes(':focus-visible')&&styles.includes('prefers-reduced-motion'),'focus/reduced motion handling missing');
expect(!/fonts\.(googleapis|gstatic)\.com/.test(styles),'remote font introduced');
expect(!workflow.includes('rsync'),'Pages must retain public-file allowlist');
expect(workflow.includes('cp -R assets'),'assets missing from deployment');
expect(/cp[^\n]+\bfr\b/.test(workflow),'French routes missing from Pages allowlist');
const actions=[...workflow.matchAll(/uses:\s+([^@\s]+)@([^\s]+)/g)];
expect(actions.length>=5&&actions.every(([, ,rev])=>/^[0-9a-f]{40}$/.test(rev)),'GitHub Actions must be pinned');
if(failures.length){console.error(failures.map(x=>'✗ '+x).join('\n'));process.exit(1)}
console.log(`✓ EN/FR routes, ${catalog.length} products, all store IDs, structured data and sitemaps`);
console.log(`✓ ${references} local references, image dimensions, keyboard hooks, static fallback and deployment allowlist`);
